version: "3.8"
services:

  metabase-app:
    image: metabase/metabase
    restart: always
    ports:
      - 13000:3000
    volumes:
      # declare your mount volume /host/dir:/container/dir
      #- ./data/metabase:/metabase-data
      - ./plugins:/plugins
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: metabase
      MB_DB_PASS: metabase
      MB_DB_HOST: host.docker.internal
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5
