version: "3.8"
services:

  metabase-app:
    image: metabase/metabase
    restart: always
    ports:
      - 3002:3000
    volumes:
      # declare your mount volume /host/dir:/container/dir
      - ./data/metabase:/metabase-data
      - ./plugins:/plugins
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: metabase
      MB_DB_PASS: metabase
      MB_DB_HOST: host.docker.internal
