version: "3.8"

networks:
  localnetwork:
    name: localnetwork

services:
  nginx:
    image: nginx
    ports:
      - 443:443
    volumes:
      - ./conf:/etc/nginx/conf.d
      - ./ssl/private:/etc/ssl/private
      - ./ssl/cert:/etc/ssl/certs