version: "3.8"
# Compose file based on oficial doc
#https://cube.dev/docs/deployment/platforms/docker

services:
  cube_api:
    restart: always
    image: cubejs/cube:v0.33.2
    container_name: cube
    ports:
      - 4000:4000
    environment:
      - CUBEJS_DB_HOST=postgres
      - CUBEJS_DB_PORT=5432
      - CUBEJS_DB_NAME=beltrano_dw
      - CUBEJS_DB_USER=postgres
      - CUBEJS_DB_PASS=postgres
      - CUBEJS_DB_TYPE=postgres
      - CUBEJS_API_SECRET=1b101a00c978eb092d4bf97840a9b127
      - CUBEJS_CUBESTORE_HOST=cubestore_router
    volumes:
      - .:/cube/conf
    depends_on:
      - postgres
      - cube_refresh_worker
      - cubestore_router
      - cubestore_worker_1
      - cubestore_worker_2

  cube_refresh_worker:
    restart: always
    image: cubejs/cube:v0.33.2
    environment:
      - CUBEJS_DB_HOST=postgres
      - CUBEJS_DB_PORT=5432
      - CUBEJS_DB_NAME=beltrano_dw
      - CUBEJS_DB_USER=postgres
      - CUBEJS_DB_PASS=postgres
      - CUBEJS_DB_TYPE=postgres
      - CUBEJS_API_SECRET=1b101a00c978eb092d4bf97840a9b127
      - CUBEJS_CUBESTORE_HOST=cubestore_router
      - CUBEJS_REFRESH_WORKER=true
    volumes:
      - .:/cube/conf

  cubestore_router:
    restart: always
    image: cubejs/cubestore:v0.33.2
    environment:
      - CUBESTORE_WORKERS=cubestore_worker_1:10001,cubestore_worker_2:10002
      - CUBESTORE_REMOTE_DIR=/cube/data
      - CUBESTORE_META_PORT=9999
      - CUBESTORE_SERVER_NAME=cubestore_router:9999
    volumes:
      - .cubestore:/cube/data

  cubestore_worker_1:
    restart: always
    image: cubejs/cubestore:v0.33.2
    environment:
      - CUBESTORE_WORKERS=cubestore_worker_1:10001,cubestore_worker_2:10002
      - CUBESTORE_SERVER_NAME=cubestore_worker_1:10001
      - CUBESTORE_WORKER_PORT=10001
      - CUBESTORE_REMOTE_DIR=/cube/data
      - CUBESTORE_META_ADDR=cubestore_router:9999
    volumes:
      - .cubestore:/cube/data
    depends_on:
      - cubestore_router

  cubestore_worker_2:
    restart: always
    image: cubejs/cubestore:v0.33.2
    environment:
      - CUBESTORE_WORKERS=cubestore_worker_1:10001,cubestore_worker_2:10002
      - CUBESTORE_SERVER_NAME=cubestore_worker_2:10002
      - CUBESTORE_WORKER_PORT=10002
      - CUBESTORE_REMOTE_DIR=/cube/data
      - CUBESTORE_META_ADDR=cubestore_router:9999
    volumes:
      - .cubestore:/cube/data
    depends_on:
      - cubestore_router

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ../_databases/postgres:/var/lib/postgresql/data
      - ../db/config/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
      - ../db/config/postgresql.conf:/etc/postgresql/postgresql.conf
      - ../db/dump/beltrano_oltp_10k_pedidos.backup:/etc/postgresql/beltrano_oltp_10k_pedidos.backup
      - ../db/dump/beltrano_dw.backup:/etc/postgresql/beltrano_dw.backup
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 5
    mem_limit: 2048M

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 443:443
    volumes:
      - ../nginx/conf:/etc/nginx/conf.d
      - ../nginx/ssl/private:/etc/ssl/private
      - ../nginx/ssl/cert:/etc/ssl/certs
    depends_on:
      - cube_api