version: "3.8"

networks:
  localnetwork:
    name: localnetwork

services:
  jupyter_lab:
    container_name: jupyter_lab
    build: .
    ports: 
      - "8888:8888"
    environment: 
      - JUPYTER_ENABLE_LAB=yes
    volumes: 
      - ./notebooks:/home/jovyan