version: "3.8"
#https://tabular.io/blog/docker-spark-and-iceberg/
#https://www.sefidian.com/2022/04/08/deploy-standalone-minio-using-docker-compose/
#https://medium.com/@jdegbun/airbyte-etl-postgres-to-s3-minio-ab788182e1fc
networks:
  labnetwork:
    name: labnetwork
  kind:
    name: kind  

services:
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ../../_data/minio_data:/data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin@minio
    command: server --console-address ":9001" /data
    networks:
     labnetwork:
        aliases:
          - warehouse.minio
     kind:
        aliases:
          - warehouse.minio
